# Generated by Django 4.1.2 on 2022-11-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('genre', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
