# Generated by Django 4.1.2 on 2022-11-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_movie_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Action', 'Action'), ('Adventure', 'Adventure'), ('Romance', 'Romance'), ('Disaster', 'Disaster'), ('Thriller', 'Thriller'), ('Musical', 'Musical'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Animation', 'Animation'), ('Family', 'Family')], default='Horror', max_length=500),
        ),
    ]
