# Generated by Django 4.1.2 on 2022-11-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='platform',
            field=models.CharField(choices=[('VHS', 'Vhs'), ('DVD', 'Dvd'), ('Blu-ray', 'Bluray')], default='Blu-ray', max_length=500),
        ),
    ]
