# Generated by Django 4.1.2 on 2022-11-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_movie_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='scene1',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='scene2',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='scene3',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='sold',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Action', 'Action'), ('Adventure', 'Adventure'), ('Romance', 'Romance'), ('Disaster', 'Disaster'), ('Thriller', 'Thriller'), ('Musical', 'Musical'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Animation', 'Animation'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('Sci-fi', 'Scifi')], default='Horror', max_length=500),
        ),
    ]
