# Generated by Django 4.1.2 on 2022-11-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_movie_scene1_movie_scene2_movie_scene3_movie_sold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('movie_id', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
